# Generated by Django 2.2 on 2019-08-01 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('closed', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Bibgroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bibgroup', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Criteria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('authorlist', models.TextField(null=True)),
                ('instlist', models.TextField(null=True)),
                ('exclstem', models.TextField(null=True)),
                ('exclvol', models.TextField(null=True)),
                ('inclstem', models.TextField(blank=True, null=True)),
                ('inclvol', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('bibgroup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bibmanage.Bibgroup')),
            ],
        ),
        migrations.CreateModel(
            name='PastSearch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('criteria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bibmanage.Criteria')),
            ],
        ),
    ]
