# Generated by Django 2.2 on 2019-09-03 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibmanage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='criteria',
            name='authorlist',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='criteria',
            name='exclstem',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='criteria',
            name='exclvol',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='criteria',
            name='instlist',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='criteria',
            name='name',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
