# Generated by Django 3.0.4 on 2020-03-17 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bibmanage', '0002_auto_20190903_1435'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='bibgroup',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bibmanage.Bibgroup'),
            preserve_default=False,
        ),
    ]
