# Generated by Django 3.0.4 on 2020-03-17 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibmanage', '0003_batch_bibgroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='modified',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='batch',
            name='closed',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
