# Generated by Django 5.0.4 on 2024-04-24 23:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("bibmanage", "0004_auto_20200317_1505"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("jnum", models.IntegerField(default=0)),
                ("anum", models.IntegerField(default=0)),
                ("daterange", models.CharField(blank=True, max_length=250, null=True)),
                ("namelist", models.TextField(blank=True, null=True)),
                (
                    "bibgroup",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bibmanage.bibgroup",
                    ),
                ),
                (
                    "username",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Journal",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("jname", models.CharField(blank=True, max_length=250, null=True)),
                ("articlenum", models.IntegerField(default=0)),
                (
                    "resultset",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bibsearch.report",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Author",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("aname", models.CharField(blank=True, max_length=250, null=True)),
                ("rart", models.IntegerField(default=0)),
                ("nrart", models.IntegerField(default=0)),
                ("rcite", models.IntegerField(default=0)),
                ("nrcite", models.IntegerField(default=0)),
                ("rfirst", models.IntegerField(default=0)),
                ("nrfirst", models.IntegerField(default=0)),
                (
                    "resultset",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bibsearch.report",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SummaryReport",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("daterange", models.CharField(blank=True, max_length=250, null=True)),
                (
                    "bibgroup",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bibmanage.bibgroup",
                    ),
                ),
                (
                    "username",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Summary",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.IntegerField(default=0)),
                ("refart", models.IntegerField(default=0)),
                ("refcite", models.IntegerField(default=0)),
                (
                    "resultset",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bibsearch.summaryreport",
                    ),
                ),
            ],
        ),
    ]
