# Generated by Django 5.0.4 on 2024-04-26 19:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("bibsearch", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Author",
            new_name="Name",
        ),
    ]
