# Generated by Django 5.0.4 on 2024-04-26 22:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bibsearch", "0002_rename_author_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="name",
            old_name="nrart",
            new_name="unrart",
        ),
        migrations.RenameField(
            model_name="name",
            old_name="nrcite",
            new_name="unrcite",
        ),
        migrations.RenameField(
            model_name="name",
            old_name="nrfirst",
            new_name="unrfirst",
        ),
        migrations.RenameField(
            model_name="name",
            old_name="rart",
            new_name="urart",
        ),
        migrations.RenameField(
            model_name="name",
            old_name="rcite",
            new_name="urcite",
        ),
        migrations.RenameField(
            model_name="name",
            old_name="rfirst",
            new_name="urfirst",
        ),
        migrations.AddField(
            model_name="name",
            name="vnrart",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="name",
            name="vnrcite",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="name",
            name="vnrfirst",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="name",
            name="vrart",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="name",
            name="vrcite",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="name",
            name="vrfirst",
            field=models.IntegerField(default=0),
        ),
    ]
