# Generated by Django 5.0.4 on 2024-04-26 23:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "bibsearch",
            "0003_rename_nrart_name_unrart_rename_nrcite_name_unrcite_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="journal",
            old_name="articlenum",
            new_name="articleunum",
        ),
        migrations.AddField(
            model_name="journal",
            name="articlevnum",
            field=models.IntegerField(default=0),
        ),
    ]
