# Generated by Django 2.2 on 2019-08-01 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bibmanage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Affil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Guess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guess', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bibcode', models.CharField(max_length=19)),
                ('query', models.CharField(max_length=100, null=True)),
                ('affils', models.TextField(null=True)),
                ('authnum', models.IntegerField(null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
                ('adminbibgroup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bibmanage.Bibgroup')),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bibmanage.Batch')),
                ('guess', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bibtool.Guess')),
                ('inst', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bibtool.Affil')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bibtool.Status')),
            ],
        ),
    ]
