# Generated by Django 2.2 on 2019-11-27 15:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bibtool', '0002_affil_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affil',
            name='username',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
