# Generated by Django 3.0.4 on 2020-03-17 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibtool', '0003_auto_20191127_1044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='affils',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='authnum',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='query',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
