# Generated by Django 3.0.4 on 2020-03-17 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibtool', '0004_auto_20200317_1330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='bibcode',
            field=models.CharField(max_length=19, unique=True),
        ),
    ]
