# Generated by Django 3.0.4 on 2020-03-26 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibtool', '0005_auto_20200317_1332'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='title',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
