# Generated by Django 3.0.4 on 2021-01-25 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bibtool', '0002_auto_20210125_1014'),
        ('bibtool', '0007_work'),
    ]

    operations = [
    ]
