# Generated by Django 3.0.4 on 2021-01-25 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bibtool', '0008_merge_20210125_1017'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('affil', models.CharField(blank=True, max_length=100, null=True)),
                ('bibcode', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bibtool.Article')),
                ('inst', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bibtool.Affil')),
            ],
        ),
    ]
