# Generated by Django 3.0.4 on 2021-01-25 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bibtool', '0009_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='affil',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='inst',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bibtool.Affil'),
        ),
        migrations.AlterField(
            model_name='author',
            name='name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
