# Generated by Django 3.0.4 on 2021-01-25 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bibtool', '0010_auto_20210125_1130'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='author',
            unique_together={('bibcode', 'name', 'affil')},
        ),
    ]
