# Generated by Django 3.0.4 on 2021-01-25 17:30

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bibmanage', '0004_auto_20200317_1505'),
        ('bibtool', '0011_auto_20210125_1152'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='author',
            name='guess',
            field=models.ForeignKey(default=6, on_delete=django.db.models.deletion.CASCADE, to='bibtool.Guess'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='author',
            name='modified',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='author',
            name='query',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='NewArticle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bibcode', models.CharField(max_length=19, unique=True)),
                ('title', models.CharField(blank=True, max_length=250, null=True)),
                ('authnum', models.IntegerField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
                ('adminbibgroup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bibmanage.Bibgroup')),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bibmanage.Batch')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bibtool.Status')),
            ],
        ),
        migrations.AlterField(
            model_name='author',
            name='bibcode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bibtool.NewArticle'),
        ),
    ]
