# Generated by Django 3.0.4 on 2021-01-25 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bibmanage', '0004_auto_20200317_1505'),
        ('bibtool', '0012_auto_20210125_1230'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='adminbibgroup',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bibmanage.Bibgroup'),
            preserve_default=False,
        ),
    ]
