# Generated by Django 3.0.4 on 2021-01-25 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bibmanage', '0004_auto_20200317_1505'),
        ('bibtool', '0013_author_adminbibgroup'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='author',
            unique_together={('bibcode', 'name', 'affil', 'adminbibgroup')},
        ),
    ]
