# Generated by Django 3.0.4 on 2021-01-26 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bibtool', '0015_author_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bibtool.Author'),
        ),
    ]
