# Generated by Django 3.0.4 on 2021-01-26 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bibtool', '0016_work_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='work',
            name='author',
        ),
    ]
