# Generated by Django 3.0.4 on 2021-02-03 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bibtool', '0021_remove_newarticle_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='status',
        ),
    ]
