# Generated by Django 3.0.4 on 2021-02-03 19:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bibtool', '0022_remove_author_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='status',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='bibtool.Status'),
            preserve_default=False,
        ),
    ]
