# Generated by Django 3.0.4 on 2021-02-03 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bibmanage', '0004_auto_20200317_1505'),
        ('bibtool', '0023_author_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newarticle',
            name='adminbibgroup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bibmanage.Bibgroup'),
        ),
    ]
