# Generated by Django 3.0.4 on 2021-02-05 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibtool', '0024_auto_20210203_1440'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='autoclass',
            field=models.BooleanField(default=False),
        ),
    ]
