# Generated by Django 3.0.4 on 2021-02-05 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibtool', '0025_author_autoclass'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='verfieds',
            field=models.BooleanField(default=False),
        ),
    ]
