# Generated by Django 3.0.4 on 2021-02-05 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bibtool', '0026_author_verfieds'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='verfieds',
            new_name='verified',
        ),
    ]
