# Generated by Django 5.0.4 on 2024-04-25 00:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_auto_20191127_1044"),
    ]

    operations = [
        migrations.CreateModel(
            name="AccessLvl",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("accesslvl", models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name="customuser",
            name="accesslvl",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="users.accesslvl",
            ),
        ),
    ]
